### ISSUE TITLE
Nvidia driver

### ISSUE THREAD

**Issue by vahedq** [rmanak/dl-workstation-setup#1]
@rmanak does this step change based on the GPU? Last time I downloaded nvidia driver from their website, and once installed it got screwed up with the pre-built generic driver that came with ubuntu. Was very painful. :)

https://github.com/rmanak/dl-workstation-setup/blob/7120102ea0bbded975df1b79a757ced46367c568/0_basic_nvidia_drivers.sh#L15

**Comment by rmanak** [comment]
@vahedq I think the nvidia driver that is in the apt-get repositories work with the majority of nvidia GPUs, yes best is to *not* download the nvidia driver from the website, but use the `apt-get install` in ubuntu. 367 is the version at the time that worked with the CUDA toolkit 8 and cuDNN5.1 versioned in the script. I believe the TensorFlow 1.4 requirement is cuDNN6.0 and may in turn need higher version of CUDA and Nvidia driver. I am actually have to do these steps one more time with cuDNN6.0 and brand new install of Ubuntu 16.04LTE :-/ so will update all these versions in the script

**Comment by vahedq** [comment]
yea downloading from website was a bad experience :-1: 
yea you're right about cuNDD6.0; had to build TF1.4 from source tho for it to work. All good for now :)
thank you!
